### ISSUE TITLE
cmd-nsc ignores ConnectTimeout env on request

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/cmd-nsc#91]
## Problem

cmd NSC has  env CONNECT_TIMEOUT https://github.com/networkservicemesh/cmd-nsc/blob/master/internal/config/config.go#L40
but the env is ignoring on request https://github.com/networkservicemesh/cmd-nsc/blob/135c6943678038b94e6a9f22391aa0cbddd3f168/main.go#L235

## Solution

Use requests with CONNECT_TIMEOUT context.

**Comment by denis-tingaikin** [comment]
cc @Bolodya1997

**Comment by Bolodya1997** [comment]
It is a timeout for dial, not for the request:
https://github.com/networkservicemesh/cmd-nsc/blob/135c6943678038b94e6a9f22391aa0cbddd3f168/main.go#L140
It is also a timeout for the cleanup action, because we don't actually want to wait for the `Close` to return, but we want the `Close` event to be propagated to the NSMgr. So it is still a timeout for networking, not for requesting.
https://github.com/networkservicemesh/cmd-nsc/blob/135c6943678038b94e6a9f22391aa0cbddd3f168/main.go#L116
